### ISSUE TITLE
The webapp doesn't run

### ISSUE THREAD

**Issue by erossini** [cgtheodorou/vibiquity#1]
I'm trying to run your code but the webapp doesn't work. What do the code suppose to work?

**Comment by cgtheodorou** [comment]
Hi, you ran the Vubiquity.Test.BasketAPI and it didnt work? if you only got a blank page its because the launchsettings were not pointing directly to the swagger endpoint which should be https://localhost:5001/swagger/index.html

I've commited the change that will launch the browser to that endpoint on startup.

**Comment by erossini** [comment]
Ok cool
